# Generated by Django 4.1.5 on 2023-02-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_name', models.CharField(max_length=50)),
                ('technology_avater', models.ImageField(blank=True, null=True, upload_to='Technology_Avater')),
            ],
        ),
    ]
