# Generated by Django 4.1.5 on 2023-02-01 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=500)),
                ('video_demo', models.URLField()),
                ('site_url', models.URLField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='Project/Cover')),
                ('client_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.client')),
                ('technology', models.ManyToManyField(null=True, to='dashboard.technology')),
            ],
        ),
    ]
