# Generated by Django 4.1.5 on 2023-02-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avater',
            field=models.ImageField(blank=True, null=True, upload_to='Employee/Avater'),
        ),
    ]
