# Generated by Django 4.1.5 on 2023-02-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_employee_avater'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='full_capture',
            field=models.ImageField(null=True, upload_to='Project/Capture'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_logo',
            field=models.ImageField(null=True, upload_to='Company_Logo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover',
            field=models.ImageField(null=True, upload_to='Project/Cover'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='technology_avater',
            field=models.ImageField(null=True, upload_to='Technology_Avater'),
        ),
    ]
