# Generated by Django 4.1.5 on 2023-02-06 03:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_blog_alter_employee_avater'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
