# Generated by Django 4.1.5 on 2023-02-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fb',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='git',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='lindin',
            field=models.URLField(null=True),
        ),
    ]
