# Generated by Django 4.1.5 on 2023-02-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_employee_fb_employee_git_employee_lindin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='twiter',
            field=models.URLField(null=True),
        ),
    ]
