# Generated by Django 4.1.5 on 2023-02-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_client_avater_alter_client_company_logo_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reating',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
