# Generated by Django 4.1.5 on 2023-02-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_client_company_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
